#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, only display username, user id, Home directory path for the user
while IFS= read -r $line;
do
   username=$(echo $line | cut -d: -f1)
   uid=$(echo $line | cut -d: -f3)
   homedir=$(echo $line | cut -d: -f6)
   
   echo "Username: $username"
   echo "User ID: $uid"
   echo "Home Directory: $homedir"
   echo "--------------------------"
done < /etc/passwd
