#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, only display username, user id, Home directory path for the user
while IFS= read -r line;
do
	echo "Username: $username" "User ID: $uid" "Home directory path for the user: $home"| cut -d: -f 1,3,6 /etc/passwd
done < /etc/passwd
