#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, only display username, user id, Home directory path for the user
fcontent="/etc/passwd"
while read -r fline
do echo "Username: $username"
    echo "User ID: $uid"
    echo "Home directory path for the user: $home"
	cut -d: -f 1,3,6 "$fline"
done < $fcontent
